name: Tag (semantic version)

on:
  workflow_run:
    workflows: ["Build"]
    types: [completed]

permissions:
  contents: write
  actions: read

jobs:
  tag:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create & push SemVer tag
        env:
          AUTO_PUSH: "true"
          GIT_REMOTE: "origin"
        run: node scripts/semver-tag.mjs